blogicum/blog/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts'
    ),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('auth/registration/', views.registration, name='registration'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path(
        'posts/<int:post_id>/edit_comment/<int:comment_id>/',
        views.edit_comment,
        name='edit_comment'
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        views.delete_comment,
        name='delete_comment'
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler403 = 'pages.views.csrf_failure'
handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/templates/includes/category_link.html
{% if post.category %}
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  {{ post.category.title }}
</a>
{% else %}
Без категории
{% endif %}

blogicum/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/brand.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %} text-white {% endif %}" href="{% url 'pages:rules' %}">
              Правила
            </a>
          </li>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'blog:create_post' %}">Написать пост</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'blog:profile' user.username %}">{{ user.username }}</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'blog:registration' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

blogicum/templates/includes/post_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ post.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ post.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if not post.is_published %}
            <p class="text-danger">Пост снят с публикации админом</p>
          {% elif post.category and not post.category.is_published %}
            <p class="text-danger">Выбранная категория снята с публикации админом</p>
          {% endif %}
          {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
          От автора <a class="text-muted" href="{% url 'blog:profile' post.author.username %}">@{{ post.author.username }}</a> в
          категории {% include "includes/category_link.html" %}
        </small>
      </h6>
      <p class="card-text">{{ post.text|truncatewords:10 }}</p>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link text-muted">Комментарии ({{ post.comment_count }})</a>
    </div>
  </div>
</div>